## Preprocessing

In [25]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("Resources/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [26]:
# Drop the non-beneficial ID columns, 'EIN'
application_df = application_df.drop(columns = ['EIN'])
application_df

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...
34294,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [27]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [28]:
# Look at NAME value counts to identify and replace with "Other"
namecount = application_df['NAME'].value_counts()
namecount

NAME
PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: count, Length: 19568, dtype: int64

In [40]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `names_replace`
names_replace = list(namecount[namecount<5].index)
names_replace

# Replace in dataframe
for name in names_replace:
    application_df['NAME'] = application_df['NAME'].replace(name,"Other")

# Check to make sure replacement was successful
application_df['NAME'].value_counts()

NAME
Other                                                                19803
PARENT BOOSTER USA INC                                                1260
TOPS CLUB INC                                                          765
UNITED STATES BOWLING CONGRESS INC                                     700
WASHINGTON STATE UNIVERSITY                                            492
                                                                     ...
GUILDS OF THE SANTA FE OPERA INC                                         5
FAMILY MOTOR COACH ASSOCIATION                                           5
JAMESTOWN SOCIETY                                                        5
MOST WORSHIPFUL PRINCE HALL GRAND LODGE OF FREE & ACCEPTED MASONS        5
PTA HAWAII CONGRESS                                                      5
Name: count, Length: 403, dtype: int64

In [44]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_counts = application_df['APPLICATION_TYPE'].value_counts()
application_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [46]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `appliction_type_to_replace`
application_types_to_replace = list(application_counts[application_counts<500].index)
application_types_to_replace
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [47]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_ACTS MINISTRY,NAME_ACTS MISSIONS,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [48]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values
y
#DROP IS SUCCESSFUL
X = application_df.drop('IS_SUCCESSFUL', axis=1).values
X
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [49]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [50]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=7
hidden_nodes_layer2=14
hidden_nodes_layer3=21
nn = tf.keras.models.Sequential()

# First hidden layer

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# Check the structure of the model
nn.summary()

c:\Users\Sreekar Thimmareddy\anaconda3\envs\dev\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_7 (Dense)                 │ (None, 7)              │         3,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 14)             │           112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,711 (14.50 KB)

 Trainable params: 3,711 (14.50 KB)

 Non-trainable params: 0 (0.00 B)

In [51]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [52]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.6761 - loss: 0.6089 - val_accuracy: 0.7839 - val_loss: 0.4528
Epoch 2/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7845 - loss: 0.4527 - val_accuracy: 0.7880 - val_loss: 0.4456
Epoch 3/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7914 - loss: 0.4359 - val_accuracy: 0.7922 - val_loss: 0.4437
Epoch 4/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7928 - loss: 0.4292 - val_accuracy: 0.7979 - val_loss: 0.4414
Epoch 5/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7926 - loss: 0.4276 - val_accuracy: 0.7932 - val_loss: 0.4442
Epoch 6/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7913 - loss: 0.4265 - val_accuracy: 0.7942 - val_loss: 0.4440
Epoch 7/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7908 - loss: 0.4298 - val_accuracy: 0.7935 - val_loss: 0.4472
Epoch 8/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7980 - loss: 0.4182 - val_accuracy: 0.7937 - val_loss: 0.4434
Epoch 9/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7971 - loss: 0.4188 - val_accuracy: 0.7930 - val_loss: 0.4449
Epoch 10/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7953 - loss: 0.4216 - val_accuracy: 0.7953 - val_loss: 0.4439
Epoch 11/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7946 - loss: 0.4166 - val_accuracy: 0.7922 - val_loss: 0.4501
Epoch 12/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7948 - loss: 0.4192 - val_accuracy: 0.7958 - val_loss: 0.4461
Epoch 13/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8054 - loss: 0.4109 - val_accuracy: 0.7971 - val_loss: 0.4493
Epoch 14/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7966 - loss: 0.4207 - val_accuracy: 0.7971 - val_loss: 0.4513
Epoch 15/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.7970 - loss: 0.4208 - val_accuracy: 0.7958 - val_loss: 0.4479
Epoch 16/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8024 - loss: 0.4124 - val_accuracy: 0.7974 - val_loss: 0.4478
Epoch 17/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8010 - loss: 0.4137 - val_accuracy: 0.7999 - val_loss: 0.4490
Epoch 18/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.8031 - loss: 0.4145 - val_accuracy: 0.7981 - val_loss: 0.4491
Epoch 19/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7973 - loss: 0.4140 - val_accuracy: 0.8002 - val_loss: 0.4490
Epoch 20/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7958 - loss: 0.4181 - val_accuracy: 0.7994 - val_loss: 0.4494
Epoch 21/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7992 - loss: 0.4142 - val_accuracy: 0.7992 - val_loss: 0.4513
Epoch 22/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7993 - loss: 0.4170 - val_accuracy: 0.7992 - val_loss: 0.4525
Epoch 23/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8039 - loss: 0.4112 - val_accuracy: 0.7966 - val_loss: 0.4505
Epoch 24/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8060 - loss: 0.4079 - val_accuracy: 0.7966 - val_loss: 0.4512
Epoch 25/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8033 - loss: 0.4128 - val_accuracy: 0.7987 - val_loss: 0.4517
Epoch 26/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8036 - loss: 0.4104 - val_accuracy: 0.7999 - val_loss: 0.4502
Epoch 27/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7994 - loss: 0.4177 - val_accuracy: 0.7974 - val_loss: 0.4535
Epoch 28/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7961 - loss: 0.4183 - val_accuracy: 0.7994 - val_loss: 0.4514
Epoch 29/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7989 - loss: 0.4107 - val_accuracy: 0.7992 - val_loss: 0.4532
Epoch 30/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7990 - loss: 0.4149 - val_accuracy: 0.8005 - val_loss: 0.4509
Epoch 31/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8007 - loss: 0.4124 - val_accuracy: 0.7999 - val_loss: 0.4517
Epoch 32/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.7963 - loss: 0.4175 - val_accuracy: 0.7989 - val_loss: 0.4500
Epoch 33/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8045 - loss: 0.4082 - val_accuracy: 0.8010 - val_loss: 0.4517
Epoch 34/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8011 - loss: 0.4109 - val_accuracy: 0.8015 - val_loss: 0.4518
Epoch 35/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8055 - loss: 0.4103 - val_accuracy: 0.8015 - val_loss: 0.4515
Epoch 36/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8013 - loss: 0.4101 - val_accuracy: 0.7984 - val_loss: 0.4546
Epoch 37/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8041 - loss: 0.4126 - val_accuracy: 0.7984 - val_loss: 0.4536
Epoch 38/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7989 - loss: 0.4173 - val_accuracy: 0.7992 - val_loss: 0.4543
Epoch 39/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8016 - loss: 0.4155 - val_accuracy: 0.7992 - val_loss: 0.4549
Epoch 40/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8021 - loss: 0.4107 - val_accuracy: 0.7999 - val_loss: 0.4533
Epoch 41/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8008 - loss: 0.4117 - val_accuracy: 0.7966 - val_loss: 0.4564
Epoch 42/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8050 - loss: 0.4111 - val_accuracy: 0.8012 - val_loss: 0.4545
Epoch 43/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8055 - loss: 0.4091 - val_accuracy: 0.7992 - val_loss: 0.4514
Epoch 44/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8022 - loss: 0.4109 - val_accuracy: 0.7955 - val_loss: 0.4587
Epoch 45/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8081 - loss: 0.4067 - val_accuracy: 0.7994 - val_loss: 0.4544
Epoch 46/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8028 - loss: 0.4114 - val_accuracy: 0.7997 - val_loss: 0.4535
Epoch 47/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8015 - loss: 0.4141 - val_accuracy: 0.7992 - val_loss: 0.4567
Epoch 48/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8008 - loss: 0.4128 - val_accuracy: 0.8005 - val_loss: 0.4586
Epoch 49/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7999 - loss: 0.4144 - val_accuracy: 0.8005 - val_loss: 0.4518
Epoch 50/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8006 - loss: 0.4121 - val_accuracy: 0.8012 - val_loss: 0.4554
Epoch 51/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8017 - loss: 0.4144 - val_accuracy: 0.8010 - val_loss: 0.4564
Epoch 52/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8032 - loss: 0.4106 - val_accuracy: 0.8012 - val_loss: 0.4530
Epoch 53/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8034 - loss: 0.4079 - val_accuracy: 0.8010 - val_loss: 0.4537
Epoch 54/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8013 - loss: 0.4112 - val_accuracy: 0.8002 - val_loss: 0.4557
Epoch 55/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7989 - loss: 0.4138 - val_accuracy: 0.7994 - val_loss: 0.4587
Epoch 56/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.8038 - loss: 0.4082 - val_accuracy: 0.8015 - val_loss: 0.4541
Epoch 57/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8036 - loss: 0.4096 - val_accuracy: 0.7994 - val_loss: 0.4545
Epoch 58/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8002 - loss: 0.4101 - val_accuracy: 0.8012 - val_loss: 0.4549
Epoch 59/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8054 - loss: 0.4054 - val_accuracy: 0.8025 - val_loss: 0.4514
Epoch 60/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8097 - loss: 0.4020 - val_accuracy: 0.8023 - val_loss: 0.4558
Epoch 61/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8014 - loss: 0.4169 - val_accuracy: 0.8025 - val_loss: 0.4525
Epoch 62/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.8012 - loss: 0.4140 - val_accuracy: 0.8012 - val_loss: 0.4580
Epoch 63/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - accuracy: 0.8004 - loss: 0.4111 - val_accuracy: 0.8036 - val_loss: 0.4536
Epoch 64/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.8013 - loss: 0.4098 - val_accuracy: 0.8012 - val_loss: 0.4590
Epoch 65/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8060 - loss: 0.4088 - val_accuracy: 0.7992 - val_loss: 0.4626
Epoch 66/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8052 - loss: 0.4108 - val_accuracy: 0.8010 - val_loss: 0.4555
Epoch 67/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8062 - loss: 0.4101 - val_accuracy: 0.8012 - val_loss: 0.4575
Epoch 68/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7999 - loss: 0.4127 - val_accuracy: 0.8005 - val_loss: 0.4565
Epoch 69/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8026 - loss: 0.4089 - val_accuracy: 0.8025 - val_loss: 0.4593
Epoch 70/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8049 - loss: 0.4077 - val_accuracy: 0.8007 - val_loss: 0.4583
Epoch 71/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8001 - loss: 0.4144 - val_accuracy: 0.8010 - val_loss: 0.4564
Epoch 72/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8045 - loss: 0.4075 - val_accuracy: 0.8007 - val_loss: 0.4529
Epoch 73/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8047 - loss: 0.4079 - val_accuracy: 0.8010 - val_loss: 0.4547
Epoch 74/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8044 - loss: 0.4065 - val_accuracy: 0.8002 - val_loss: 0.4574
Epoch 75/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8038 - loss: 0.4099 - val_accuracy: 0.8015 - val_loss: 0.4561
Epoch 76/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8032 - loss: 0.4107 - val_accuracy: 0.8005 - val_loss: 0.4563
Epoch 77/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8034 - loss: 0.4085 - val_accuracy: 0.7999 - val_loss: 0.4600
Epoch 78/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8057 - loss: 0.4066 - val_accuracy: 0.8015 - val_loss: 0.4556
Epoch 79/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8086 - loss: 0.4033 - val_accuracy: 0.8025 - val_loss: 0.4588
Epoch 80/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8056 - loss: 0.4049 - val_accuracy: 0.8028 - val_loss: 0.4566
Epoch 81/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8008 - loss: 0.4144 - val_accuracy: 0.8015 - val_loss: 0.4555
Epoch 82/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8071 - loss: 0.4061 - val_accuracy: 0.8015 - val_loss: 0.4591
Epoch 83/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8037 - loss: 0.4090 - val_accuracy: 0.8012 - val_loss: 0.4558
Epoch 84/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8074 - loss: 0.4027 - val_accuracy: 0.7994 - val_loss: 0.4542
Epoch 85/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8038 - loss: 0.4079 - val_accuracy: 0.8005 - val_loss: 0.4593
Epoch 86/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8047 - loss: 0.4089 - val_accuracy: 0.8038 - val_loss: 0.4542
Epoch 87/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8025 - loss: 0.4126 - val_accuracy: 0.8031 - val_loss: 0.4546
Epoch 88/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8059 - loss: 0.4074 - val_accuracy: 0.8023 - val_loss: 0.4573
Epoch 89/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8062 - loss: 0.4025 - val_accuracy: 0.8041 - val_loss: 0.4552
Epoch 90/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8055 - loss: 0.4071 - val_accuracy: 0.8023 - val_loss: 0.4539
Epoch 91/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8072 - loss: 0.4076 - val_accuracy: 0.8012 - val_loss: 0.4538
Epoch 92/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8032 - loss: 0.4106 - val_accuracy: 0.8031 - val_loss: 0.4537
Epoch 93/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8092 - loss: 0.4050 - val_accuracy: 0.7997 - val_loss: 0.4554
Epoch 94/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8048 - loss: 0.4055 - val_accuracy: 0.8033 - val_loss: 0.4545
Epoch 95/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8084 - loss: 0.4067 - val_accuracy: 0.8054 - val_loss: 0.4559
Epoch 96/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8040 - loss: 0.4052 - val_accuracy: 0.7999 - val_loss: 0.4598
Epoch 97/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8061 - loss: 0.4067 - val_accuracy: 0.8036 - val_loss: 0.4572
Epoch 98/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8059 - loss: 0.4074 - val_accuracy: 0.8023 - val_loss: 0.4586
Epoch 99/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8038 - loss: 0.4109 - val_accuracy: 0.8041 - val_loss: 0.4564
Epoch 100/100
684/684 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8044 - loss: 0.4103 - val_accuracy: 0.8018 - val_loss: 0.4577

In [53]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - 2ms/step - accuracy: 0.7886 - loss: 0.4614
Loss: 0.46137094497680664, Accuracy: 0.7885714173316956

In [54]:
# Export our model to HDF5 file
nn.save("./AlphabetSoupCharity_OPTIMISATION.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.